name: Publish Docker Images
on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          build-args: |
            IN_CONTACT_BOT_TOKEN=${{ secrets.IN_CONTACT_BOT_TOKEN }}
          tags: yzhbankov/in-contact:latest
