name: Publish Docker Images
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('v', '')
            const dash_index = no_v.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)
            core.setOutput('no-dash', no_dash)

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./dev-ops/Dockerfile
          build-args: |
            IN_CONTACT_BOT_TOKEN=${{ secrets.IN_CONTACT_BOT_TOKEN }}
            IN_CONTACT_SMTP_USER=${{ secrets.IN_CONTACT_SMTP_USER }}
            IN_CONTACT_SMTP_PWD=${{ secrets.IN_CONTACT_SMTP_PWD }}
            IN_CONTACT_SMTP_HOST=${{ secrets.IN_CONTACT_SMTP_HOST }}
            IN_CONTACT_SMTP_FROM=${{ secrets.IN_CONTACT_SMTP_FROM }}
            IN_CONTACT_MONITOR_API_BASE_URL=${{ secrets.IN_CONTACT_MONITOR_API_BASE_URL }}
          tags: |
            yzhbankov/in-contact:${{ steps.set_version.outputs.no-dash }}
            yzhbankov/in-contact:latest
