name: check
on: [ pull_request ]
jobs:
  check:
    name: Format, Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Run Prettier and Eslint
        run: yarn code
