name: Publish Docker Images
on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Print Secrets
        run: echo "Username ${{ secrets.DOCKER_HUB_USERNAME }} Token ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}"

      - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
